# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20190724_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
